# Generated by Django 2.1.7 on 2019-04-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_role_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.UserGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='API.Role'),
        ),
    ]
